#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
hours=0
while ((hours <= 12)); do
    echo "Hour: $hours"
    min=1
        while ((min < 60)); do
            echo "$min"
            ((min++))
            done
    ((hours++))
done